"""Add required_days_off and flexible_days_off fields

Revision ID: 1a9ee5283098
Revises: ce97277993e1
Create Date: 2025-10-21 14:40:47.586526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9ee5283098'
down_revision = 'ce97277993e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_days_off', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('flexible_days_off', sa.String(length=100), nullable=True))
        batch_op.drop_column('required_day_off')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_day_off', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('flexible_days_off')
        batch_op.drop_column('required_days_off')

    # ### end Alembic commands ###
