"""Initial migration

Revision ID: 427c565582d8
Revises: 
Create Date: 2025-10-25 14:27:11.447332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427c565582d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('suggested_schedule', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('constraints_met', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('shift_length', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('is_per_diem', sa.Boolean(), nullable=True),
    sa.Column('area_restrictions', sa.String(length=200), nullable=True),
    sa.Column('required_days_off', sa.String(length=100), nullable=True),
    sa.Column('flexible_days_off', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('required_rn_count', sa.Integer(), nullable=True),
    sa.Column('required_tech_count', sa.Integer(), nullable=True),
    sa.Column('required_scope_tech_count', sa.Integer(), nullable=True),
    sa.Column('special_rules', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['staff_area.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index('idx_shift_date_area', ['date', 'area_id'], unique=False)
        batch_op.create_index('idx_shift_date_staff', ['date', 'staff_id'], unique=False)

    op.create_table('time_off_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_request_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_request_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_request_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_request_status'))
        batch_op.drop_index(batch_op.f('ix_time_off_request_start_date'))
        batch_op.drop_index(batch_op.f('ix_time_off_request_end_date'))

    op.drop_table('time_off_request')
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index('idx_shift_date_staff')
        batch_op.drop_index('idx_shift_date_area')

    op.drop_table('shift')
    op.drop_table('staff_area')
    op.drop_table('staff')
    op.drop_table('ai_suggestion')
    # ### end Alembic commands ###
