"""Add indexes and eager loading optimization

Revision ID: 5ad4f619aaa5
Revises: 4026de76dcdd
Create Date: 2025-10-25 14:21:59.809330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad4f619aaa5'
down_revision = '4026de76dcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index('idx_shift_date_area', ['date', 'area_id'], unique=False)
        batch_op.create_index('idx_shift_date_staff', ['date', 'staff_id'], unique=False)

    with op.batch_alter_table('time_off_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_request_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_request_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_request_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_request_status'))
        batch_op.drop_index(batch_op.f('ix_time_off_request_start_date'))
        batch_op.drop_index(batch_op.f('ix_time_off_request_end_date'))

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index('idx_shift_date_staff')
        batch_op.drop_index('idx_shift_date_area')

    # ### end Alembic commands ###
